import os
import uuid
import streamlit as st
import pandas as pd
from fpdf import FPDF
import streamlit.components.v1 as components
from qdrant_client import QdrantClient
from qdrant_client.http import models
from sentence_transformers import SentenceTransformer
import json
from config import URL, API_KEY


# --- 1. CONFIGURATION ---
st.set_page_config(
    page_title="Tunisia Smartphone Search - Find Your Perfect Device",
    layout="wide",
    page_icon="📱",
    initial_sidebar_state="collapsed"
)
st.markdown("""
    <style>
    /* Add a professional card look to each product container */
    [data-testid="stVerticalBlock"] > div:has(div.stMarkdown) {
        background-color: #ffffff;
        border: 1px solid #f0f2f6;
        padding: 15px;
        border-radius: 15px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.05);
        transition: transform 0.2s;
    }
    [data-testid="stVerticalBlock"] > div:has(div.stMarkdown):hover {
        transform: translateY(-5px);
        box-shadow: 0 10px 15px rgba(0,0,0,0.1);
    }
    </style>
""", unsafe_allow_html=True)

if 'compare_list' not in st.session_state:
    st.session_state.compare_list = {}
if 'page_offset' not in st.session_state:
    st.session_state.page_offset = 0
if 'total_searches' not in st.session_state:
    st.session_state.total_searches = 0

# --- 2. UTILITY FUNCTIONS ---

def scroll_to_top():
    """Scroll to top smoothly using JavaScript"""
    components.html(
        "<script>window.parent.document.querySelector('.main').scrollTo({top: 0, behavior: 'smooth'});</script>",
        height=0
    )

def get_stars(rating):
    """Convert numeric rating to stars"""
    try:
        r = int(float(rating))
        return "⭐" * min(max(r, 1), 5)
    except:
        return "N/A"

def format_price_display(price, currency="DT"):
    """Format price with proper styling"""
    try:
        return f"{float(price):,.0f} {currency}"
    except:
        return f"{price} {currency}"

def generate_comparison_pdf(data_dict):
    """Generate a professional landscape PDF with comparison table"""
    pdf = FPDF(orientation='L', unit='mm', format='A4')
    pdf.add_page()
    
    # Color scheme
    PINK = (233, 30, 99)
    TURQUOISE = (64, 224, 208)
    NAVY = (10, 22, 40)
    LILAC = (200, 162, 200)

    # Title
    pdf.set_font("Arial", "B", 24)
    pdf.set_text_color(*PINK)
    pdf.cell(0, 15, "Tunisia Smartphone Search", ln=True, align="C")
    
    pdf.set_font("Arial", "B", 16)
    pdf.set_text_color(*TURQUOISE)
    pdf.cell(0, 10, "Product Comparison Report", ln=True, align="C")
    pdf.ln(5)

    # Create DataFrame
    df = pd.DataFrame(data_dict).T
    
    # Define required columns
    required_cols = ['name', 'display_price', 'brand', 'color', 'availability']
    for col in required_cols:
        if col not in df.columns:
            df[col] = "N/A"
    
    features = [
        ('name', 'Product Name'), 
        ('brand', 'Brand'),
        ('display_price', 'Price'), 
        ('color', 'Color'),
        ('availability', 'Availability')
    ]

    # Header row
    pdf.set_font("Arial", "B", 10)
    pdf.set_fill_color(*LILAC)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(45, 12, "Feature", border=1, fill=True, align='C')
    
    for name in df['name']:
        pdf.cell(48, 12, str(name)[:20], border=1, fill=True, align='C')
    pdf.ln()

    # Data rows
    pdf.set_text_color(*NAVY)
    for key, label in features:
        pdf.set_font("Arial", "B", 9)
        pdf.set_fill_color(245, 247, 250)
        pdf.cell(45, 10, label, border=1, fill=True)
        
        pdf.set_font("Arial", "", 9)
        for val in df[key]:
            clean_val = str(val) if val is not None else "N/A"
            pdf.cell(48, 10, clean_val[:22], border=1)
        pdf.ln()

    # Footer
    pdf.ln(10)
    pdf.set_font("Arial", "I", 8)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5, "Generated by Tunisia Smartphone Search | Your Smart Shopping Assistant", align='C')

    return bytes(pdf.output())

# --- 3. LOAD CSS ---
if os.path.exists("style.css"):
    with open("style.css") as f:
        st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)

# --- 4. HEADER IMAGE & BRANDING ---
image_path = r"c:\Users\user\Pictures\Screenshots\Capture d'écran 2026-01-23 142433.png"

if os.path.exists(image_path):
    col1, col2, col3 = st.columns([1, 3, 1])
    with col2:
        st.image(image_path, use_container_width=True)
else:
    # Fallback header if image not found
    st.markdown("""
        <div style='text-align: center; padding: 2rem; background: linear-gradient(135deg, #E91E63 0%, #40E0D0 100%); border-radius: 20px; margin-bottom: 2rem;'>
            <h1 style='color: white; font-size: 3rem; margin: 0; text-shadow: 2px 2px 4px rgba(0,0,0,0.2);'>📱 Tunisia Smartphone Search</h1>
            <p style='color: white; font-size: 1.2rem; margin-top: 0.5rem;'>Find Your Perfect Device at the Best Price</p>
        </div>
    """, unsafe_allow_html=True)

# --- 5. LOAD RESOURCES ---
@st.cache_resource
def load_resources():
    client = QdrantClient(url=URL, api_key=API_KEY, timeout=60)
    model = SentenceTransformer('clip-ViT-B-32')
    return client, model

client, model = load_resources()
collection_name = "products2"

# --- 6. HERO SECTION ---
st.markdown("""
    <div style='text-align: center; margin: 2rem 0;'>
        <h1 style='font-size: 3.5rem; font-weight: 800; background: linear-gradient(135deg, #E91E63 0%, #40E0D0 100%); 
                   -webkit-background-clip: text; -webkit-text-fill-color: transparent; margin-bottom: 0.5rem;'>
            WELCOME TO TUNISIA SMARTPHONE SEARCH 📱
        </h1>
        <p class='subtitle' style='font-size: 1.3rem; color: #718096; font-weight: 400;'>
            🔍 Smart Search · 💰 Best Prices · ⚡ Lightning Fast · 🎯 AI-Powered
        </p>
    </div>
""", unsafe_allow_html=True)

# --- 7. SEARCH UI ---
st.markdown("<h2 style='color: #E91E63; margin-top: 2rem;'>🔎 Find Your Perfect Product</h2>", unsafe_allow_html=True)

# First row: Search and Budget
col1, col2, col3 = st.columns([3, 2, 2])
with col1:
    query = st.text_input(
        "Search by name, brand, or model...", 
        placeholder="Example: iPhone 15, Samsung Galaxy, Xiaomi Redmi...",
        help="Enter any keyword to search across all products"
    )
with col2:
    budget = st.number_input(
        "Maximum Budget (DT)", 
        min_value=0, 
        max_value=20000, 
        value=5000, 
        step=100,
        help="Set your budget limit"
    )
with col3:
    category_filter = st.selectbox(
        "Category", 
        ["Tous", "Smartphone", "Ordinateur", "Accessoires","Réfrigérateur", "Casque & Écouteurs","Électroménager"],
        help="Filter by product category"
    )

# Second row: Color and Image upload
col4, col5 = st.columns([1, 1])
with col4:
    color_filter = st.selectbox(
        "Preferred Color 🎨", 
        ["Toutes", "Noir", "Bleu", "Vert", "Rouge", "Blanc", "Gold", "Silver", "Violet"],
        help="Filter by color preference"
    )
with col5:
    uploaded_file = st.file_uploader(
        "Or Search by Image 📸", 
        type=['jpg', 'jpeg', 'png'],
        help="Upload a phone image to find similar models"
    )

# --- 8. STATS DASHBOARD ---
if st.session_state.total_searches > 0:
    stat_col1, stat_col2, stat_col3 = st.columns(3)
    with stat_col1:
        st.markdown(f"""
            <div style='background: linear-gradient(135deg, #E91E63 0%, #FF6B9D 100%); padding: 1.5rem; border-radius: 16px; text-align: center; box-shadow: 0 4px 15px rgba(233, 30, 99, 0.3);'>
                <h3 style='color: white; margin: 0; font-size: 2rem;'>{st.session_state.total_searches}</h3>
                <p style='color: white; margin: 0; opacity: 0.9;'>Total Searches</p>
            </div>
        """, unsafe_allow_html=True)
    with stat_col2:
        st.markdown(f"""
            <div style='background: linear-gradient(135deg, #40E0D0 0%, #7FEFDC 100%); padding: 1.5rem; border-radius: 16px; text-align: center; box-shadow: 0 4px 15px rgba(64, 224, 208, 0.3);'>
                <h3 style='color: white; margin: 0; font-size: 2rem;'>{len(st.session_state.compare_list)}</h3>
                <p style='color: white; margin: 0; opacity: 0.9;'>Products Comparing</p>
            </div>
        """, unsafe_allow_html=True)
    with stat_col3:
        st.markdown(f"""
            <div style='background: linear-gradient(135deg, #FFD700 0%, #FFA500 100%); padding: 1.5rem; border-radius: 16px; text-align: center; box-shadow: 0 4px 15px rgba(255, 215, 0, 0.3);'>
                <h3 style='color: white; margin: 0; font-size: 2rem;'>{budget:,.0f} DT</h3>
                <p style='color: white; margin: 0; opacity: 0.9;'>Your Budget</p>
            </div>
        """, unsafe_allow_html=True)

# --- 9. COMPARISON SECTION ---
if st.session_state.compare_list:
    st.markdown("---")
    st.markdown("<h2 style='color: #E91E63;'>⚖️ Product Comparison</h2>", unsafe_allow_html=True)
    
    with st.expander("📊 View Detailed Comparison Table", expanded=True):
        comp_df = pd.DataFrame([
            {
                "🏷️ Product": p.get('name', 'N/A')[:45] + "...",
                "🏢 Brand": p.get('brand', 'N/A'),
                "💰 Price": p.get('display_price', 'N/A'),
                "🎨 Color": p.get('color', 'N/A'),
                "📦 Stock": p.get('availability', 'N/A')
            } for p in st.session_state.compare_list.values()
        ])
        
        st.dataframe(comp_df, use_container_width=True, hide_index=True)
        
        st.markdown("<br>", unsafe_allow_html=True)
        
        btn_col1, btn_col2, btn_col3 = st.columns([1, 1, 1])
        
        with btn_col1:
            pdf_data = generate_comparison_pdf(st.session_state.compare_list)
            st.download_button(
                "📥 Download PDF Report", 
                data=pdf_data, 
                file_name=f"smartphone_comparison_{pd.Timestamp.now().strftime('%Y%m%d_%H%M%S')}.pdf", 
                mime="application/pdf",
                use_container_width=True
            )
        
        with btn_col2:
            # Export as CSV
            csv = comp_df.to_csv(index=False).encode('utf-8')
            st.download_button(
                "📊 Export as CSV",
                data=csv,
                file_name=f"comparison_{pd.Timestamp.now().strftime('%Y%m%d_%H%M%S')}.csv",
                mime="text/csv",
                use_container_width=True
            )
        
        with btn_col3:
            if st.button("🗑️ Clear Comparison List", use_container_width=True, type="secondary"):
                st.session_state.compare_list = {}
                st.rerun()

st.markdown("---")

# --- 10. SEARCH EXECUTION ---
search_vector = None
search_performed = False

if uploaded_file is not None:
    from PIL import Image
    img = Image.open(uploaded_file)
    
    img_col1, img_col2, img_col3 = st.columns([1, 2, 1])
    with img_col2:
        st.image(img, caption="🔍 Searching for similar phones...", use_container_width=True)
    
    search_vector = model.encode(img).tolist()
    search_performed = True
    st.session_state.total_searches += 1
    
elif query:
    search_vector = model.encode(query).tolist()
    search_performed = True
    st.session_state.total_searches += 1

if search_vector:
    try:
        # Build filter conditions
        filter_conditions = [
            models.FieldCondition(
                key="price", 
                range=models.Range(lte=float(budget))
            )
        ]
        
        if category_filter != "Tous":
            filter_conditions.append(
                models.FieldCondition(
                    key="category",
                    match=models.MatchValue(value=category_filter)
                )
            )
        
        if color_filter != "Toutes":
            filter_conditions.append(
                models.FieldCondition(
                    key="color",
                    match=models.MatchValue(value=color_filter)
                )
            )
        
        # Execute search
        results = client.search(
            collection_name=collection_name,
            query_vector=search_vector, 
            limit=100,
            query_filter=models.Filter(must=filter_conditions)
        )
        
        # --- Display Results ---
        if len(results) == 0:
            st.info("🔍 No products found matching your criteria. Try adjusting your filters!")
        else:
            # Results header
            st.markdown(f"""
                <div style='background: linear-gradient(135deg, rgba(233, 30, 99, 0.1) 0%, rgba(64, 224, 208, 0.1) 100%); 
                            padding: 1.5rem; border-radius: 16px; margin: 2rem 0; text-align: center; border: 2px solid #E91E63;'>
                    <h2 style='color: #E91E63; margin: 0;'>🎯 Found {len(results)} Products Matching Your Search!</h2>
                </div>
            """, unsafe_allow_html=True)
            
            # Setup Pagination
            items_per_page = 9
            total_pages = (len(results) // items_per_page) + (1 if len(results) % items_per_page > 0 else 0)
            current_idx = st.session_state.get('page_offset', 0)
            page_results = results[current_idx : current_idx + items_per_page]

            # Product Grid
            for i in range(0, len(page_results), 3):
                cols = st.columns(3)
                for j, hit in enumerate(page_results[i:i+3]):
                    with cols[j]:
                        with st.container():
                            p = hit.payload
                            p_id = hit.id
                            
                            # 1. Product Image
                            img_url = str(p.get('image', ''))
                            if img_url and img_url.lower() != 'nan' and img_url.startswith('http'):
                                st.markdown(f"""
                                    <div style="display: flex; justify-content: center; align-items: center; height: 200px; margin-bottom: 10px;">
                                        <img src="{img_url}" style="max-height: 100%; max-width: 100%; object-fit: contain;">
                                     </div>
                                """, unsafe_allow_html=True)
                            else:
                                st.markdown("""
                                    <div style='background: linear-gradient(135deg, #E91E63 0%, #40E0D0 100%); 
                                                padding: 4rem; text-align: center; border-radius: 16px;'>
                                        <p style='color: white; font-size: 3rem; margin: 0;'>📱</p>
                                    </div>
                                """, unsafe_allow_html=True)

                            # 2. Discount Badge
                            if p.get('has_discount'):
                                discount_pct = p.get('discount_percentage', 0)
                                st.markdown(f"""
                                    <div style="background: linear-gradient(135deg, #ff4444 0%, #cc0000 100%); 
                                                color: white; padding: 8px; border-radius: 12px; text-align: center; 
                                                margin: 10px 0; font-weight: bold; box-shadow: 0 4px 10px rgba(255, 68, 68, 0.3);
                                                animation: pulse 2s infinite;">
                                        🔥 SPECIAL OFFER -{discount_pct}%
                                    </div>
                                """, unsafe_allow_html=True)

                            # 3. Availability Status
                            status = str(p.get('availability', 'En Stock'))
                            if status == "En Stock":
                                st.success(f"✅ {status}")
                            elif "Rupture" in status or "Out of Stock" in status:
                                st.error(f"❌ {status}")
                            else:
                                st.warning(f"⏳ {status}")
                            
                            # 4. Product Name
                            product_name = p.get('name', 'Product Name')[:50]
                            st.markdown(f"<h3 style='color: #1A202C; font-size: 1.1rem; font-weight: 700; margin: 0.5rem 0;'>{product_name}...</h3>", unsafe_allow_html=True)
                            
                            # 5. Price Display
                            if p.get('original_price') and p.get('has_discount'):
                                price_html = f"""
                                    <div style='margin: 1rem 0;'>
                                        <span style="text-decoration: line-through; color: #999; font-size: 0.95rem; display: block;">
                                            {p.get('display_original_price', '')}
                                        </span>
                                        <span style="color: #E91E63; font-size: 1.8rem; font-weight: 800; font-family: 'Space Mono', monospace;">
                                            {p.get('display_price', 'N/A')}
                                        </span>
                                    </div>
                                """
                            else:
                                price_html = f"""
                                    <div style="color: #E91E63; font-size: 1.6rem; font-weight: 800; margin: 1rem 0; font-family: 'Space Mono', monospace;">
                                        {p.get('display_price', 'N/A')}
                                    </div>
                                """
                            
                            st.markdown(price_html, unsafe_allow_html=True)
                            
                            # 6. Product Details
                            detail_col1, detail_col2 = st.columns(2)
                            with detail_col1:
                                st.markdown(f"""
                                    <div style='background: #1A202C; color: white; padding: 0.4rem; border-radius: 6px; 
                                    font-size: 0.8rem; text-align: center; font-weight: 600; margin-bottom: 5px;'>
                                        🏢 {p.get('brand', 'Brand')}
                                     </div>""", unsafe_allow_html=True)
                            with detail_col2:
                                st.markdown(f"""
                                    <div style='background: #E91E63; color: white; padding: 0.4rem; border-radius: 6px; 
                                    font-size: 0.8rem; text-align: center; font-weight: 600; margin-bottom: 5px;'>
                                        🎨 {p.get('color', 'Color')}
                                    </div>""", unsafe_allow_html=True)
                            
                            # 7. Action Buttons
                            compare_label = "✅ Selected for Comparison" if p_id in st.session_state.compare_list else "⚖️ Add to Compare"
                            button_type = "secondary" if p_id in st.session_state.compare_list else "primary"
                            
                            if st.button(compare_label, key=f"compare_{p_id}", use_container_width=True, type=button_type):
                                if p_id in st.session_state.compare_list:
                                    del st.session_state.compare_list[p_id]
                                    st.toast("❌ Removed from comparison", icon="🗑️")
                                else:
                                    if len(st.session_state.compare_list) < 5:
                                        st.session_state.compare_list[p_id] = p
                                        st.toast("✅ Added to comparison!", icon="⚖️")
                                    else:
                                        st.warning("⚠️ Maximum 5 products for comparison")
                                st.rerun()
                            
                            # 8. View Offer Button
                            offer_url = p.get('url', '#')
                            if offer_url and offer_url != '#':
                                st.link_button("🛒 View Full Details & Buy", offer_url, use_container_width=True)
                            else:
                                st.button("🛒 View Details (Coming Soon)", use_container_width=True, disabled=True)

            # Pagination Navigation
            st.markdown("---")
            st.markdown("<div style='margin: 3rem 0;'>", unsafe_allow_html=True)
            
            nav_col1, nav_col2, nav_col3 = st.columns([1, 2, 1])
            
            with nav_col1:
                if st.button("⬅️ Previous Page", use_container_width=True, disabled=(st.session_state.page_offset < items_per_page)):
                    st.session_state.page_offset -= items_per_page
                    scroll_to_top()
                    st.rerun()
            
            with nav_col2:
                current_page = (st.session_state.page_offset // items_per_page) + 1
                st.markdown(
                    f"""<div style='text-align: center; padding: 1rem; background: white; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);'>
                        <p style='margin: 0; font-size: 1.3rem; font-weight: 700; font-family: "Space Mono", monospace; color: #E91E63;'>
                            Page <span style='color: #40E0D0;'>{current_page}</span> of <span style='color: #40E0D0;'>{total_pages}</span>
                        </p>
                    </div>""", 
                    unsafe_allow_html=True
                )
            
            with nav_col3:
                if st.button("Next Page ➡️", use_container_width=True, disabled=((st.session_state.page_offset + items_per_page) >= len(results))):
                    st.session_state.page_offset += items_per_page
                    scroll_to_top()
                    st.rerun()
            
            st.markdown("</div>", unsafe_allow_html=True)
                        
    except Exception as e:
        st.error(f"❌ Search Error: {e}")
        st.info("💡 Try adjusting your search criteria or contact support if the problem persists.")

elif not search_performed:
    # Welcome message when no search is performed
    st.markdown("""
        <div style='text-align: center; padding: 4rem 2rem; background: white; border-radius: 20px; margin: 3rem 0; box-shadow: 0 10px 30px rgba(0,0,0,0.1);'>
            <div style='font-size: 5rem; margin-bottom: 1rem;'>🔍</div>
            <h2 style='color: #E91E63; margin-bottom: 1rem;'>Ready to Find Your Perfect Smartphone?</h2>
            <p style='font-size: 1.2rem; color: #718096; max-width: 600px; margin: 0 auto;'>
                Enter a search term above or upload an image to discover the best smartphone deals in Tunisia!
            </p>
            <div style='margin-top: 2rem; padding: 1.5rem; background: linear-gradient(135deg, rgba(233, 30, 99, 0.1) 0%, rgba(64, 224, 208, 0.1) 100%); border-radius: 12px;'>
                <p style='margin: 0; font-size: 1rem; color: #1A202C;'>
                    <strong>💡 Pro Tips:</strong> Search by brand (Samsung, iPhone), model (Galaxy S24), or even upload a photo of the phone you like!
                </p>
            </div>
        </div>
    """, unsafe_allow_html=True)

# --- 11. FOOTER ---
st.markdown("---")
st.markdown("""
    <div style='text-align: center; padding: 2rem; background: linear-gradient(135deg, #0A1628 0%, #1A2B4A 100%); border-radius: 20px; margin-top: 3rem;'>
        <h3 style='color: white; margin-bottom: 1rem;'>Tunisia Smartphone Search</h3>
        <p style='color: rgba(255,255,255,0.7); margin-bottom: 1rem;'>Your AI-Powered Smart Shopping Assistant</p>
        <p style='color: rgba(255,255,255,0.5); font-size: 0.9rem;'>
            🚀 Powered by Advanced AI · 🇹🇳 Made for Tunisia · 💰 Saving You Money
        </p>
    </div>
""", unsafe_allow_html=True) 